language: rust
rust:
  - stable
  - beta
  - nightly-2019-05-22
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

branches:
  only:
  - master

cache:
  yarn: true
  cargo: true
  directories:
    - borsh-rs/target

before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

install:
  - cargo build --verbose --manifest-path=borsh-rs/Cargo.toml
  - yarn install

build:
  - cargo build --verbose --manifest-path=borsh-rs/Cargo.toml
  - cargo test --verbose --manifest-path=borsh-rs/Cargo.toml
  - yarn test