[package]
name = "borsh-derive"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
borsh-derive-internal = { path = "../borsh-derive-internal" }
syn = {version = "0.15.34", features = ["full", "fold"] }

